name: CI test PR query

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Git SHA to look up'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy
        run: echo noop
