name: Test version

on:
  workflow_dispatch:
  #pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version
      
      - name: Debug
        run: |
          echo "Version: ${{ steps.get-version.outputs.version }}"
